---
# found good example at https://github.com/vbotka/ansible-freebsd-mysql/blob/master/tasks/secret.yml
- name: Check that the default mysql_secret file is exists
  stat:
    path: "{{ mysql_secret_file }}"
  register: secret_file_result

- name: Get MySQL root pass
  command: tail -1 "{{ mysql_secret_file }}"
  register: bsd_mysql_secret
  when: secret_file_result.stat.exists
- debug: 
    var: bsd_mysql_secret['stdout']

- name: Set new password from temporary password
  shell: |
    mysql --connect-expired-password -u root -p'{{ bsd_mysql_secret['stdout'] }}' -NBe 'ALTER USER "root"@"localhost" IDENTIFIED BY "{{ mysql_root_password }}"'
  when: secret_file_result.stat.exists

- name: Delete default mysql_secret
  file:
    state: absent
    path: "{{ mysql_secret_file }}"
